image: node:dubnium-alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - install
  - lint
  - test

Install:
  stage: install
  script:
    - npm install
  except: tags

Lint:
  stage: lint
  script:
    - npm run lint
  dependencies:
    - Install
  except: tags

Test:
  stage: test
  script:
    - npm test
  dependencies:
    - Install
  except: tags
